### ISSUE TITLE
Elasticsearch + Kibana compatibility layer

### ISSUE THREAD

**Issue by brandonros** [bayard-search/bayard#1]
I feel like there is room in the "market" for log indexing (that can be used by Kibana) that isn't as heavy as Elasticsearch. Do you have any interest in making the `bayard` API respond to `Kibana` Elasticsearch format API requests and serve Elasticsearch API format responses?

**Comment by mosuka** [comment]
Hi @brandonros ,

Thank you for your comment.
This project is just getting started and there are many higher priority tasks. And I don't consider Supporting their APIs at this time, because to need to follow their specification changes.
IMO, if I want to visualize the data, I'll consider developing a plug-in for adopting a product that neutral position such as Grafana rather than supporting their API.

Thanks,
